name: 'Aggregation'

on:
  push:
    paths: [ '.github/workflows/aggregation.yml' ]
  pull_request:
    paths: [ '.github/workflows/aggregation.yml' ]

env:
  BUILD_DIR: build-directory

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_DIR }}
          key: build-${{ github.sha }}-${{ matrix.os }}

      - shell: bash
        run: |
          mkdir $BUILD_DIR
          echo "Run your build command here"
          echo "This is a fake ${{ matrix.os }} build artifact" >${BUILD_DIR}/${{ matrix.os }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_DIR }}
          restore-keys: |
            build-${{ github.sha }}-

      - shell: bash
        run: |
          for i in $( ls $BUILD_DIR ); do
            cat $BUILD_DIR/$i
          done
