name: Docker networking


on:
  push:
    branches: [master]

env:
  CURL: curlimages/curl

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      nginx-service:
        image: nginx
      nginx-service-published:
        image: nginx
        ports:
          - 8080:8080
    steps:
      - name: local nginx
        run: >
          docker run -d
          --name nginx-local
          --cidfile nginx-local.cid
          nginx

      - name: local nginx in host network
        run: >
          docker run -d
          --name nginx-local-host
          --cidfile nginx-local-host.cid
          --network "host"
          nginx

      - name: local nginx in service network
        run: >
          docker run -d
          --name nginx-local-service
          --cidfile nginx-local-service.cid
          --network "${{ job.container.network }}"
          nginx

      - name: curl
        run: |
          docker run $CURL http://nginx-service:8080 || true
          docker run $CURL http://nginx-service-published:8080 || true
          docker run $CURL http://localhost:8080 || true
          docker run $CURL http://nginx-local:8080 || true
          docker run $CURL http://nginx-local-host:8080 || true
          docker run $CURL http://nginx-local-service:8080 || true

      - name: curl host
        run: |
          docker run --network "host" $CURL http://nginx-service:8080 || true
          docker run --network "host" $CURL http://nginx-service-published:8080 || true
          docker run --network "host" $CURL http://localhost:8080 || true
          docker run --network "host" $CURL http://nginx-local:8080 || true
          docker run --network "host" $CURL http://nginx-local-host:8080 || true
          docker run --network "host" $CURL http://nginx-local-service:8080 || true

      - name: curl service
        run: |
          docker run --network "${{ job.container.network }}" $CURL http://nginx-service:8080 || true
          docker run --network "${{ job.container.network }}" $CURL http://nginx-service-published:8080 || true
          docker run --network "${{ job.container.network }}" $CURL http://localhost:8080 || true
          docker run --network "${{ job.container.network }}" $CURL http://nginx-local:8080 || true
          docker run --network "${{ job.container.network }}" $CURL http://nginx-local-host:8080 || true
          docker run --network "${{ job.container.network }}" $CURL http://nginx-local-service:8080 || true
