name: 'Ignore skipped 2'

on:
  push:
    paths: [ '.github/workflows/ignore-skipped-2.yml' ]
  pull_request:
    paths: [ '.github/workflows/ignore-skipped-2.yml' ]

jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-latest
    steps:
      - run: true

  job-b:
    name: Job B
    runs-on: ubuntu-latest
    needs: job-a
    if: false
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-c:
    name: Job C
    runs-on: ubuntu-latest
    needs: job-a
    if: false
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-d:
    name: Job D
    needs: job-a
    runs-on: ubuntu-latest
    if: false
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-bcd1:
    name: Job bcd 1
    runs-on: ubuntu-latest
    needs: [ job-b, job-c, job-d ]
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-bcd2:
    name: Job bcd 2
    runs-on: ubuntu-latest
    needs: [ job-b, job-c, job-d ]
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"
