name: 'Ignore skipped'

on:
  push:
    paths: [ '.github/workflows/ignore-skipped.yml' ]
  pull_request:
    paths: [ '.github/workflows/ignore-skipped.yml' ]

jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-latest
    steps:
      - run: true

  job-b:
    name: Job B
    runs-on: ubuntu-latest
    needs: job-a
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-c:
    name: Job C
    runs-on: ubuntu-latest
    needs: job-a
    if: false
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-d:
    name: Job D
    needs: job-a
    runs-on: ubuntu-latest
    if: false
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-e:
    name: Job E
    needs: job-a
    runs-on: ubuntu-latest
    if: false
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-bcd1:
    name: Job BCD 1
    runs-on: ubuntu-latest
    needs: [ job-b, job-c, job-d ]
    if: ${{ contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-bcd2:
    name: Job BCD 2
    runs-on: ubuntu-latest
    needs: [ job-b, job-c, job-d ]
    if: ${{ !failure() && contains(needs.*.result, 'success') }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-bcd3:
    name: Job BCD 3
    runs-on: ubuntu-latest
    needs: [ job-b, job-c, job-d ]
    if: ${{ always() && contains(needs.*.result, 'success') }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-bcd4:
    name: Job BCD 4
    runs-on: ubuntu-latest
    needs: [ job-b, job-c, job-d ]
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-bcd5:
    name: Job BCD 5
    runs-on: ubuntu-latest
    needs: [ job-b, job-c, job-d ]
    if: ${{ always() && !failure() && contains(needs.*.result, 'success') }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"


  job-cde1:
    name: Job CDE 1
    runs-on: ubuntu-latest
    needs: [ job-c, job-d, job-e ]
    if: ${{ contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-cde2:
    name: Job CDE 2
    runs-on: ubuntu-latest
    needs: [ job-c, job-d, job-e ]
    if: ${{ !failure() && contains(needs.*.result, 'success') }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-cde3:
    name: Job CDE 3
    runs-on: ubuntu-latest
    needs: [ job-c, job-d, job-e ]
    if: ${{ always() && contains(needs.*.result, 'success') }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-cde4:
    name: Job CDE 4
    runs-on: ubuntu-latest
    needs: [ job-c, job-d, job-e ]
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"

  job-cde5:
    name: Job CDE 5
    runs-on: ubuntu-latest
    needs: [ job-c, job-d, job-e ]
    if: ${{ always() && !failure() && contains(needs.*.result, 'success') }}
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS"
