name: 'Install package'

on:
  push:
    paths: [ '.github/workflows/install-package.yml' ]
  pull_request:
    paths: [ '.github/workflows/install-package.yml' ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install runc
