name: 'Install package'

on:
  push:
    paths: [ '.github/workflows/install-package.yml' ]
  pull_request:
    paths: [ '.github/workflows/install-package.yml' ]

jobs:
  runs-on: ubuntu-latest
  install:
    steps:
      - run: sudo apt-get install runc
