name: 'Get output from environment'

on:
  push:
    paths: [ '.github/workflows/output-from-env.yml' ]
  pull_request:
    paths: [ '.github/workflows/output-from-env.yml' ]

jobs:
  job-a:
    env:
      MY_SITE:
    runs-on: ubuntu-latest
    steps:
      - run: "echo MY_SITE: $MY_SITE"
      - run: "echo 'MY_SITE=https://example.org' >> $GITHUB_ENV" 
      - run: "echo MY_SITE: $MY_SITE"
