name: 'Get output from environment'

on:
  push:
    paths: [ '.github/workflows/output-from-env.yml' ]
  pull_request:
    paths: [ '.github/workflows/output-from-env.yml' ]

jobs:
  job-a:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ env.TEST }}
    env:
      TEST: 'hello'
      TEST2: ${{ TEST }}
    steps:
      - run: |
          echo "TEST: $TEST"
          echo "TEST2: $TEST2"

  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
      - run: echo ${{ needs.job-a.outputs.test }}
